version: '3.3'
services:
  decadevs_docker_oluwatosin:
    container_name: decadevs-docker-oluwatosin
    image: decadevs-docker-oluwatosin
    build: ./
    ports:
      - "8532:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: tosin
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: 123456